name: demo workflows
on:
  push:
    path:
      - "/home/namdao/projects/final_project/tests/test_api.py"
jobs:
  demo_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print latest content
        run: cat /home/namdao/projects/final_project/tests/test_api.py


