name: demo workflows
on:
  push:
    path:
      - "tests/test_api.py"
  pull_request:
    path:
      - "pull_request_test.txt"
jobs:
  demo_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print latest content
        run: |
          if [ "$GITHUB_EVENT_NAME" == "push" ]; then 
            cat tests/test_api.py
          elif [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            cat pull_request_test.txt
          else
            echo "no event name found"
            exit 1
          fi


